name: axe DevHub
description: Get the axe DevHub status for a commit

inputs:
  api_key:
    description: axe DevHub API Key
    required: true
  project_id:
    description: the ID of your Axe Developer Hub project
    required: false
  server_url:
    description: axe server URL
    required: false
    default: https://axe.deque.com
  retry_count:
    description: number of times to attempt fetching the commit status
    required: false
    default: 10
  enable_a11y_threshold:
    description: Enable the a11y threshold, which will cause the action to fail if the number of violations is greater than the threshold
    required: false
    default: "false"
  commit_sha:
    description: Override the commit SHA to check status for
    required: false
    default: ${{ github.sha }}
  github_token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

outputs:
  project:
    description: Project name
    value: ${{ steps.main.outputs.project }}
  project_id:
    description: Project ID
    value: ${{ steps.main.outputs.project_id }}
  axe_url:
    description: Axe URL for the commit's issues
    value: ${{ steps.main.outputs.axe_url }}
  issue_count:
    description: Number of violations found
    value: ${{ steps.main.outputs.issue_count }}
  issues_over_a11y_threshold:
    description: Whether the number of violations is over your a11y threshold
    value: ${{ steps.main.outputs.issues_over_a11y_threshold }}

runs:
  using: composite
  steps:
    - name: Find current PR
      uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # tag=v1.3.3
      id: find_pr
    - name: Get axe DevHub commit overview
      id: main
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        API_KEY: ${{ inputs.api_key }}
        SERVER_URL: ${{ inputs.server_url }}
        RETRY_COUNT: ${{ inputs.retry_count }}
        COMMIT_SHA: ${{ github.sha }}
        ENABLE_A11Y_THRESHOLD: ${{ inputs.enable_a11y_threshold }}
        PROJECT_ID: ${{ inputs.project_id }}
    - name: Add a comment with accessibility violations over a11y threshold into the current PR
      if: ${{ failure() && inputs.enable_a11y_threshold == 'true' }}
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # tag=v2.9.4
      with:
        header: axe-devhub
        message: |
          axe DevHub found **${{ steps.main.outputs.issue_count }}** accessibility violations in this PR.
          axe DevHub found **${{ steps.main.outputs.issues_over_a11y_threshold }}** accessibility violations over your a11y threshold in this PR.

          See the full report on [axe DevHub](${{ steps.main.outputs.axe_url }}).
        GITHUB_TOKEN: ${{ inputs.github_token }}
        number: ${{ steps.find_pr.outputs.pr }}
    - name: Add a comment with accessibility violations into the current PR
      if: ${{ failure() && inputs.enable_a11y_threshold == 'false' }}
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # tag=v2.9.4
      with:
        header: axe-devhub
        message: |
          axe DevHub found **${{ steps.main.outputs.issue_count }}** accessibility violations in this PR.

          See the full report on [axe DevHub](${{ steps.main.outputs.axe_url }}).
        GITHUB_TOKEN: ${{ inputs.github_token }}
        number: ${{ steps.find_pr.outputs.pr }}
    - name: Hide a previously added comment if there are no violations.
      if: ${{ success() }}
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # tag=v2.9.4
      with:
        header: axe-devhub
        hide: true
        hide_classify: OUTDATED
        GITHUB_TOKEN: ${{ inputs.github_token }}
        number: ${{ steps.find_pr.outputs.pr }}
